# admin.yml

rgs_admin_index:
    path:     /
    defaults: { _controller: 'RgsAdminModule:AdminController:index' }

rgs_admin_login:
    path:     /login
    defaults:
        _controller: 'UserModule:SecurityController:login'
        _redirect: rgs_admin_index
        _roles: [ROLE_ADMIN]
        view: 'file:[RgsAdminModule]Security/login.php'

rgs_admin_logout:
    path:     /logout
    defaults:
        _controller: 'UserModule:SecurityController:logout'
        _redirect: rgs_admin_login

# content management
rgs_admin_gestion_advertisement:
    path:     /advertisements
    defaults: { content_manager: 'Rgs\AdminModule\Util\AdvertisementsManager' }

rgs_admin_gestion_article:
    path:     /articles
    defaults: { content_manager: 'Rgs\AdminModule\Util\ArticlesManager' }

rgs_admin_gestion_category:
    path:     /categories/
    defaults: { content_manager: 'Rgs\AdminModule\Util\CategoriesManager' }

rgs_admin_gestion_etat:
    path:     /etats
    defaults: { content_manager: 'Rgs\AdminModule\Util\StatesManager'}

rgs_admin_gestion_marque:
    path:     /marques
    defaults: { content_manager: 'Rgs\AdminModule\Util\BrandsManager' }

rgs_admin_gestion_media:
    path:     /gestion_media
    defaults: { _template: 'file:[RgsAdminModule]Content/mediaManager.php' }

# content forms
rgs_admin_advertisements_add:
    path:     /advertisements/edit
    defaults:
        _controller: 'RgsAdminModule:AdminController:editAdvertisement'

rgs_admin_advertisements_edit:
    path:     /advertisements/edit/{id}/{slug}
    defaults:
        _controller: 'RgsAdminModule:AdminController:editAdvertisement'
    requirements:
        id: \d+

rgs_admin_advertisements_edit_2:
    path:     /advertisements/edit/{id}/
    defaults:
        _controller: 'RgsAdminModule:AdminController:editAdvertisement'
    requirements:
        id: \d+

rgs_admin_articles_add:
    path:     /articles/edit
    defaults:
        _controller: 'RgsAdminModule:AdminController:editArticle'

rgs_admin_articles_edit:
    path:     /articles/edit/{id}/{slug}
    defaults:
        _controller: 'RgsAdminModule:AdminController:editArticle'
    requirements:
        id: \d+

rgs_admin_articles_edit_2:
    path:     /articles/edit/{id}/
    defaults:
        _controller: 'RgsAdminModule:AdminController:editArticle'
    requirements:
        id: \d+

rgs_admin_categories_add:
    path:     /categories/edit
    defaults:
        _controller: 'RgsAdminModule:AdminController:editCategory'

rgs_admin_categories_edit:
    path:     /categories/edit/{id}/{slug}
    defaults:
        _controller: 'RgsAdminModule:AdminController:editCategory'
    requirements:
        id: \d+

rgs_admin_categories_edit_2:
    path:     /categories/edit/{id}/
    defaults:
        _controller: 'RgsAdminModule:AdminController:editCategory'
    requirements:
        id: \d+

rgs_admin_etats_add:
    path:     /etats/edit
    defaults:
        _controller: 'RgsAdminModule:AdminController:editEtat'

rgs_admin_etats_edit:
    path:     /etats/edit/{id}/{slug}
    defaults:
        _controller: 'RgsAdminModule:AdminController:editEtat'
    requirements:
        id: \d+

rgs_admin_etats_edit_2:
    path:     /etats/edit/{id}/
    defaults:
        _controller: 'RgsAdminModule:AdminController:editEtat'
    requirements:
        id: \d+

rgs_admin_marques_add:
    path:     /marques/edit
    defaults:
        _controller: 'RgsAdminModule:AdminController:editMarque'

rgs_admin_marques_edit:
    path:     /marques/edit/{id}/{slug}
    defaults:
        _controller: 'RgsAdminModule:AdminController:editMarque'
    requirements:
        id: \d+

rgs_admin_marques_edit_2:
    path:     /marques/edit/{id}/
    defaults:
        _controller: 'RgsAdminModule:AdminController:editMarque'
    requirements:
        id: \d+

# users management
rgs_admin_gestion_users:
    path:     /users/
    defaults:
        _controller: 'RgsAdminModule:UserManagerController:gestionUser'
        _permissions: ['ROLE_SUPER_ADMIN']

rgs_admin_gestion_groups:
    path:     /groups/
    defaults:
        _controller: 'RgsAdminModule:GroupManagerController:gestionGroup'
        _permissions: ['ROLE_SUPER_ADMIN']

# users forms
rgs_admin_users_add:
    path:     /users/edit
    defaults:
        _controller: 'RgsAdminModule:UserManagerController:editUser'
        _permissions: ROLE_SUPER_ADMIN

rgs_admin_users_edit:
    path:     /users/edit/{id}/
    defaults:
        _controller: 'RgsAdminModule:UserManagerController:editUser'
        _permissions: ROLE_SUPER_ADMIN
    requirements:
        id: \d+

# reservations management
rgs_admin_gestion_reservations:
    path:     /reservations/
    defaults:
        _controller: 'RgsAdminModule:ReservationManagerController:gestionReservation'

rgs_admin_gestion_expired_reservations:
    path:     /expired/
    defaults:
        _controller: 'RgsAdminModule:ReservationManagerController:gestionReservation'
        state: expired

# reservations forms
rgs_admin_reservations_details:
    path:     /{state}/details/{id}/
    defaults:
        _controller: 'RgsAdminModule:ReservationManagerController:detailsReservation'
        state: reservations
    requirements:
        id: \d+
        state: reservations|expired

# user requests management
rgs_admin_gestion_requests:
    path:     /requests/
    defaults:
        _controller: 'RgsAdminModule:RequestManagerController:gestionRequest'