<?php

namespace Rgs\UserModule\Entity\Repository;

use Doctrine\ORM\EntityRepository;

use Rgs\UserModule\Entity\Group as UserGroup;

/**
 * Group
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Group extends EntityRepository
{
	public function lock(array $ids, $locked = UserGroup::LOCKED){
		foreach($ids as $id){
			$this->lockOneUser($id, $locked);
		}
	}

	public function lockOneUser($id, $locked = UserGroup::LOCKED){
		$qb = $this->createQueryBuilder('g');

		return $qb->update('UserModule:Group', 'g')
			->set('g.locked', ':locked')
			->where('g.id = :id')
			->setParameter('locked', $locked)
			->setParameter('id', $id)
			->getQuery()
			->execute();
	}
}
