# les parametres pour acceder a la base de donnees
imports:
    - { resource: parameters.yml }
    # - { resource: doctrine.yml }
    - { resource: managers.yml }
    - { resource: framework.yml }

services:
    mailer:
        class:    Novice\Test\Mailer
        arguments:  [%mailer_transport%]
    newsletter_manager:
        class:    Novice\Test\NewsletterManager
        calls:
            - [setMailer, ["@mailer"]]
        lazy: true
        scope: request