# routes.yml

route7:
    path:     /foo/bar/foo/goo
    defaults: { _controller: 'MyController::fooAction' }

route6:
    path:     /foo/bar/foo/bar/goo
    defaults: { _controller: 'MyController::foobarAction' }

routeTest:
    path:     /doctrine2-tuto/src/test-repository.{ext}
    defaults:
        _controller: 'AcmeModule:AcmeController:index'
        zdata: 'blabla'
        get_data: 'blabla'
    requirements:
        ext: php|html

routeSecTest:
    path:     /{ext}
    defaults:
        _controller: 'AcmeModule:AcmeController:index'
        zdata: 'blabla'
        get_data: 'blabla'
    requirements:
        ext: php|html

routeComments:
    path:     /comments
    defaults:
        _controller: 'AcmeModule:AcmeController:comments'


routeAdmin:
    path:     /admin/index
    defaults:
        _controller: 'AcmeModule:AcmeAdminController:index'

routeConnexion:
    path:     /login
    defaults:
        _controller: 'AcmeModule:ConnexionController:login'

routeConnexionAngular:
    path:     /login/angular
    defaults:
        _controller: 'AcmeModule:ConnexionController:loginAngular'

routeDeconnexion:
    path:     /logout
    defaults:
        _controller: 'AcmeModule:ConnexionController:logout'

routeRegister:
    path:     /register
    defaults:
        _controller: 'AcmeModule:ConnexionController:register'

routeRegisterConfirm:
    path:     /login/confirm/{token}/{login}
    defaults:
        _controller: 'AcmeModule:ConnexionController:registerConfirm'

createCategorieTest:
    path:     test/create_categorie
    defaults:
        _controller: 'AcmeModule:AcmeController:createCategorie'

createArticleTest:
    path:     test/create_article
    defaults:
        _controller: 'AcmeModule:AcmeController:createArticle'

scannerDir:
    path:     test/scanner_dir/images
    defaults:
        _controller: 'AcmeModule:AcmeController:scanDir'

saluto:
    path:     /saluto
    defaults:
        _controller: 'SalutoModule:SalutoController:index'