
framework:
    asset:
        strategy:
            service:    asset.packages.version_strategy
        packages:
            urls:
                cdnjs:  [ https://cdnjs.cloudflare.com/ajax/libs/ ] 
            paths:
                css:   /css
                js:    /js
                jquery:    /js/jquery
                js_custom:   /js/custom
                img:   /img
                upload:   /upload
                plugins:   /plugins
        
    router:
        resource: "%app.root_dir%/config/sgbd/routing.yml"
        options:
            matcher_class: Novice\Routing\Matcher\RedirectableUrlMatcher
            matcher_base_class: Novice\Routing\Matcher\RedirectableUrlMatcher

    templating:
        debug:  false
    
    translator: { fallbacks: [fr,en] }

services:
    asset.packages.version_strategy:
        class:    Symfony\Component\Asset\VersionStrategy\StaticVersionStrategy
        arguments:  [%asset.version% , %asset.version_format%]