# routing.yml

rgs_catalog:
    resource: @StagesModule/Resources/config/routing/routes.xml
    host: "{domain}"
    prefix:   /
    defaults:
        domain: localhost
    requirements:
        domain: localhost|127.0.0.1