<?php

namespace Rgs\CatalogModule\Entity\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AdvertisementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertisementRepository extends \Doctrine\ORM\EntityRepository
{
}
