<?php

namespace Rgs\CatalogModule\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

use Rgs\CatalogModule\Entity\Brand;

/**
 * BrandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandRepository extends EntityRepository
{
	public function publish(array $ids, $publish = Brand::PUBLISHED){
		foreach($ids as $id){
			$this->publishOneBrand($id, $publish);
		}
	}

	public function publishOneBrand($id, $publish = Brand::PUBLISHED){
		$qb = $this->createQueryBuilder('m');

		return $qb->update('RgsCatalogModule:Brand', 'm')
			->set('m.published', ':published')
			->where('m.id = :id')
			->setParameter('published', $publish)
			->setParameter('id', $id)
			->getQuery()
			->execute();
	}

	public function deleteOneById($id)
	{
		$qb = $this->createQueryBuilder('m');

		return $qb->delete('RgsCatalogModule:Brand', 'm')
			->where('m.id = :id')
			->setParameter('id', $id)
			->getQuery()
			->execute();
	}

	public function deleteByIds(array $ids)
	{
		foreach($ids as $id){
			$this->deleteOneById($nsmc, $ids);
		}
	}

	public function getBrands($limit = 20, $page = 1, $orderBy = 'm.name', $ascending = 'ASC')
	{
		$qb = $this->createQueryBuilder('m');
		
		$qb	->orderBy($orderBy, $ascending)
			->setFirstResult(($page-1) * $limit)
			->setMaxResults($limit);

		return new Paginator($qb);
	}
	
	public function findBrands($limit = 20, $page = 1, $where = array(), $orderBy = array())
	{
		$qb = $this->createQueryBuilder('m');
		
		$i = 1;
		foreach($where as $k => $v){
			$qb->andWhere($qb->expr()->eq($k, '?'.$i))
				->setParameter($i, $v);
			$i++;
		}

		if(empty($orderBy))
			$orderBy = array('m.name' => 'ASC');

		foreach($orderBy as $k => $v){
			$qb	->addOrderBy($k, $v);
		}
		
		$qb ->setFirstResult(($page-1) * $limit)
			->setMaxResults($limit);

		return new Paginator($qb);
	}

	public function countBrands($where = array())
	{
		$qb = $this->createQueryBuilder('m');

		$qb->select('count(m.id)');

		$i = 1;
		foreach($where as $k => $v){
			$qb->andWhere($qb->expr()->eq($k, '?'.$i))
				->setParameter($i, $v);
			$i++;
		}

		return $qb->getQuery()->getSingleScalarResult();
	}

	public function getFrontQB(){
				$b = 'brand';

				$qb = $this->createQueryBuilder($b);
				//$qb->select($b.'.id');

				$andModule = $qb->expr()->andX();
				$andModule->add($qb->expr()->eq($b.'.published', ':bp'));

				$qb->andWhere($andModule)
				->setParameter('bp', Brand::PUBLISHED);

				return $qb;
	}
}
