<?php

namespace Rgs\CatalogModule\Entity\Repository;

use Rgs\CatalogModule\Entity\Request;

/**
 * RequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestRepository extends \Doctrine\ORM\EntityRepository
{
}
