<?php

namespace Rgs\CatalogModule\Entity\Repository;

/**
 * ReservationArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationArticleRepository extends \Doctrine\ORM\EntityRepository
{
}
