# Doctrine Configuration
managers:
    activate: true
    connections:
        default:
            driver:   %database_driver%
            host:     %database_host%
            port:     %database_port%
            dbname:   %database_name%
            user:     %database_user%
            password: %database_password%
            charset:  utf8
        second:
            driver:   %database_driver%
            host:     %database_host%
            port:     %database_port%
            dbname:   test
            user:     %database_user%
            password: %database_password%
            charset:  utf8
    auto_generate_proxy_classes: ALWAYS
    # hydrators:
    #    ListHydrator:    \Acme\Hydrators\ListHydrator
    #dql:
        #string_functions:
        #    test_string: Acme\HelloBundle\DQL\StringFunction
        #    second_string: Acme\HelloBundle\DQL\SecondStringFunction
        #numeric_functions:
        #    test_numeric: Acme\HelloBundle\DQL\NumericFunction
        #datetime_functions:
        #    test_datetime: Acme\HelloBundle\DQL\DatetimeFunction

services:
    # gedmo extension listeners
    
    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: managers.event_subscriber }
        calls:
            # you should set the used annotation reader to listener, to avoid creating new one for mapping drivers
            - [ setAnnotationReader, [ @managers.cached.annotation_reader ] ]

    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: managers.event_subscriber }
        calls:
            - [ setAnnotationReader, [ @managers.cached.annotation_reader ] ]

    gedmo.listener.blameable:
        class: Gedmo\Blameable\BlameableListener
        tags:
            - { name: managers.event_subscriber }
        calls:
            - [ setAnnotationReader, [ @managers.cached.annotation_reader ] ]
            - [ setUserValue, [ anonym ] ]

    gedmo.listener.uploadable:
        class: Gedmo\Uploadable\UploadableListener
        tags:
            - { name: managers.event_subscriber }
        calls:
            - [ setAnnotationReader, [ @managers.cached.annotation_reader ] ]
            - [ setDefaultPath, [ %web.upload_dir% ] ]


    gedmo.listener.tree:
        class: Gedmo\Tree\TreeListener
        tags:
            - { name: managers.event_subscriber }
        calls:
            - [ setAnnotationReader, [ @managers.cached.annotation_reader ] ]

    gedmo.listener.translatable:
        class: Gedmo\Translatable\TranslatableListener
        tags:
            - { name: managers.event_subscriber }
        calls:
            # current translation locale should be set from session or hook later into the listener
            # most important, before entity manager is flushed
            - [ setTranslatableLocale, [ en ] ]
            - [ setDefaultLocale, [ en ] ]
            - [ setAnnotationReader, [ @managers.cached.annotation_reader ] ]

    #gedmo.listener.loggable:
    #    class: Gedmo\Loggable\LoggableListener
    #    tags:
    #        - { name: managers.event_subscriber }
    #    calls:
    #        - [ setUsername, [ admin ] ]
    #        - [ setAnnotationReader, [ @managers.cached.annotation_reader ] ]

    #gedmo.listener.sortable:
    #    class: Gedmo\Sortable\SortableListener
    #    tags:
    #        - { name: managers.event_subscriber }
    #    calls:
    #        - [ setAnnotationReader, [ @managers.cached.annotation_reader ] ]